### ISSUE TITLE
Can’t connect, keeps saying reconnecting ?

### ISSUE THREAD

**Issue by nodecentral** [estbeetoo/node-red-contrib-kodi#6]
Hi,

Can I confirm the exact details that should be in the kodi configuration to create the connection? Currently everything I’ve tried won’t connect, keeps trying but never succeeds ?

I’ve confirm it’s accessible via the web setting in Kodi, and tried a couple of ports the 9090 shown in your example and the 8189 in the kodi web interface option ?

There is no password set, just username kodi, any ideas what I might be missing ?  

Many thanks

**Comment by aborovsky** [comment]
Thank you for your attention to current lib!
Please, check that you enabled remote control.
<img width="511" alt="Снимок экрана 2019-07-23 в 13 58 38" src="https://user-images.githubusercontent.com/1669420/61707012-31722b00-ad52-11e9-9a27-32ea56fdaeb5.png">
