### ISSUE TITLE
UnhandledPromiseRejectionWarning: ReferenceError: err is not defined

### ISSUE THREAD

**Issue by mlfunston** [estbeetoo/node-red-contrib-kodi#7]
I'm getting a lot of these errors in the node red logs: _UnhandledPromiseRejectionWarning: ReferenceError: err is not defined_, per below:

```
(node:13175) UnhandledPromiseRejectionWarning: ReferenceError: err is not defined
    at /home/pi/.node-red/node_modules/node-red-contrib-kodi/kodi.js:179:46
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
(node:13175) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 65)
```

The current version on NPM is v0.2.7. I see you have fixed this bug in v0.2.8 and I've tested it now and confirm it fixes the above errors. Do you want to publish v0.2.8 back to NPM now?

Thanks for the great tool!

**Comment by aborovsky** [comment]
Thank you for help! v0.2.8 published: https://www.npmjs.com/package/node-red-contrib-kodi/v/0.2.8
